In [4]:
import torch

x = torch.empty(2, 2,3) # scalar
x

tensor([[[-5.2409e+11,  4.5615e-41,  2.8714e-34],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00]],

        [[ 2.8708e-34,  0.0000e+00,  2.8773e-34],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [5]:
x = torch.rand(5, 3)
x

tensor([[0.5107, 0.0991, 0.1535],
        [0.3930, 0.0509, 0.4945],
        [0.1616, 0.5943, 0.2116],
        [0.8690, 0.3061, 0.2750],
        [0.6964, 0.6305, 0.8542]])

In [6]:
x = torch.zeros(5, 3)
x
x.size()
x.dtype

torch.float32

In [7]:
x = torch.zeros(5, 3, dtype=torch.float16)
x
x.size()
x.dtype

torch.float16

In [8]:
x = torch.tensor([5.5, 3])
x.size()

torch.Size([2])

In [9]:
x = torch.tensor([5.5, 3], requires_grad=True)

# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print(x,y)
z = x + y
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())


tensor([[0.0789, 0.0631],
        [0.2492, 0.8384]]) tensor([[0.1270, 0.4485],
        [0.8746, 0.9926]])
tensor([[0.9519, 0.2121, 0.6849],
        [0.2816, 0.4545, 0.3767],
        [0.7236, 0.0351, 0.7564],
        [0.1232, 0.8318, 0.7540],
        [0.8835, 0.2911, 0.2587]])
tensor([0.9519, 0.2816, 0.7236, 0.1232, 0.8835])
tensor([0.2816, 0.4545, 0.3767])
tensor(0.4545)
0.4545220136642456


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())
a = torch.ones(5)

b = a.numpy()
print(b)
print(type(b))

a.add_(1)
a
b

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


array([2., 2., 2., 2., 2.], dtype=float32)

In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)

# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
