In [2]:
import torch
# The autograd package provides automatic differentiation 
# for all operations on Tensors

# requires_grad = True -> tracks all operations on the tensor. 
x = torch.randn(3, requires_grad=True)
y = x + 2
print(x) # created by the user -> grad_fn is None
print(y)
print(y.grad_fn)

tensor([-0.4137,  2.0282, -0.0943], requires_grad=True)
tensor([1.5863, 4.0282, 1.9057], grad_fn=<AddBackward0>)


In [3]:
z = y * y * 3
print(z)
z = z.mean()
print(z)
z.backward()
print(x.grad) # dz/dx

tensor([ 7.5487, 48.6801, 10.8949], grad_fn=<MulBackward0>)
tensor(22.3746, grad_fn=<MeanBackward0>)
tensor([3.1725, 8.0565, 3.8114])


In [4]:
x = torch.randn(3, requires_grad=True)

y = x * 2
for _ in range(10):
    y = y * 2

print(y)
print(y.shape)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float32)
y.backward(v)
print(x.grad)

a = torch.randn(2, 2)
print(a.requires_grad)
b = ((a * 3) / (a - 1))
print(b.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([-1697.4473, -1948.1617, -1178.3973], grad_fn=<MulBackward0>)
torch.Size([3])
tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])
False
None
True


In [5]:
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
b = a.detach()
print(b.requires_grad)

a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)


True
False
True
False


In [17]:
weights = torch.ones(4, requires_grad=True)
# print(weights)
for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    model_output.backward()
    
    print(weights.grad)

    # optimize model, i.e. adjust weights...
    with torch.no_grad():
        weights -= 0.1 * weights.grad
        print(weights)

    # this is important! It affects the final weights & output
    weights.grad.zero_()

print(weights)
print(model_output)

tensor([3., 3., 3., 3.])
tensor([0.7000, 0.7000, 0.7000, 0.7000], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([0.4000, 0.4000, 0.4000, 0.4000], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
